"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-26

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('use_case', sa.String(length=80), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_tier', sa.String(length=20), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('billing', sa.String(length=20), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('seller', sa.String(length=120), nullable=False),
    sa.Column('seller_rating', sa.Float(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('avg_completion_time', sa.String(length=20), nullable=False),
    sa.Column('model_provider', sa.String(length=40), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('deployer_wallet', sa.String(length=64), nullable=True),
    sa.Column('input_price_per_1m', sa.Integer(), nullable=False),
    sa.Column('output_price_per_1m', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderation_reports',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('agent', sa.String(length=120), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('reporter', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('seller', sa.String(length=120), nullable=False),
    sa.Column('agent', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('from_addr', sa.String(length=64), nullable=False),
    sa.Column('to_addr', sa.String(length=64), nullable=False),
    sa.Column('amount_usdc', sa.BigInteger(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chain_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_transactions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chain_transactions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_chain_transactions_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_chain_transactions_tx_hash'), ['tx_hash'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_agent_id'), ['agent_id'], unique=False)

    op.create_table('verification_entries',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('seller', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted', sa.String(length=20), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_entries')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_agent_id'))

    op.drop_table('reviews')
    op.drop_table('orders')
    with op.batch_alter_table('chain_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_transactions_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_chain_transactions_ts'))
        batch_op.drop_index(batch_op.f('ix_chain_transactions_kind'))
        batch_op.drop_index(batch_op.f('ix_chain_transactions_agent_id'))

    op.drop_table('chain_transactions')
    op.drop_table('payouts')
    op.drop_table('moderation_reports')
    op.drop_table('agents')
    # ### end Alembic commands ###
