"""custody chain

Tables and agent columns for docs/decisions/0001-custody-chain.md §11.
Existing agents get their public id (AGT-XXXX-XXXX-C) backfilled from their
primary key with the same rule the model uses for new rows.

Revision ID: 0002_custody_chain
Revises: 0001_initial
Create Date: 2026-09-26

"""
from alembic import op
import sqlalchemy as sa

from app.common.agent_ids import from_db_id


# revision identifiers, used by Alembic.
revision = '0002_custody_chain'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_sub', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('weekly_cap_micro', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('humans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_humans_world_sub'), ['world_sub'], unique=True)

    op.create_table('used_id_token_jtis',
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('engagements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('buyer_human_id', sa.Integer(), nullable=True),
    sa.Column('buyer_address', sa.String(length=64), nullable=True),
    sa.Column('parent_engagement_id', sa.String(length=32), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('sow_json', sa.Text(), nullable=True),
    sa.Column('sow_hash', sa.String(length=66), nullable=True),
    sa.Column('total_micro', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('mandate_id', sa.String(length=32), nullable=True),
    sa.Column('ens_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['buyer_human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['parent_engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagements_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagements_buyer_human_id'), ['buyer_human_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagements_parent_engagement_id'), ['parent_engagement_id'], unique=False)

    op.create_table('ens_names',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('node', sa.String(length=66), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('parent_name', sa.String(length=255), nullable=True),
    sa.Column('engagement_id', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('expiry', sa.BigInteger(), nullable=True),
    sa.Column('records', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('tx_hashes', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['parent_name'], ['ens_names.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('ens_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ens_names_parent_name'), ['parent_name'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.String(length=32), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('acceptance', sa.Text(), nullable=False),
    sa.Column('amount_micro', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('auto_release_at', sa.DateTime(), nullable=True),
    sa.Column('released_ledger_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'idx', name='uq_milestones_engagement_idx')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('screenings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('hop', sa.String(length=32), nullable=False),
    sa.Column('engagement_id', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('chain_address', sa.String(length=64), nullable=False),
    sa.Column('screened_address', sa.String(length=64), nullable=True),
    sa.Column('network', sa.String(length=32), nullable=True),
    sa.Column('verdict', sa.String(length=12), nullable=False),
    sa.Column('cap_micro', sa.BigInteger(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('toxic_score', sa.Integer(), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=False),
    sa.Column('risk_group', sa.String(length=32), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('fail_closed', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenings_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('action_json', sa.Text(), nullable=False),
    sa.Column('action_hash', sa.String(length=66), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('flow', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('state_param', sa.String(length=64), nullable=True),
    sa.Column('pkce_verifier', sa.String(length=128), nullable=True),
    sa.Column('device_code', sa.String(length=255), nullable=True),
    sa.Column('user_code', sa.String(length=32), nullable=True),
    sa.Column('verification_uri', sa.String(length=512), nullable=True),
    sa.Column('verification_uri_complete', sa.String(length=1024), nullable=True),
    sa.Column('poll_interval', sa.Integer(), nullable=True),
    sa.Column('next_poll_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('human_sub', sa.String(length=255), nullable=True),
    sa.Column('id_token_jti', sa.String(length=255), nullable=True),
    sa.Column('auth_time', sa.BigInteger(), nullable=True),
    sa.Column('acr', sa.String(length=255), nullable=True),
    sa.Column('failure_code', sa.String(length=40), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('engagement_id', sa.String(length=32), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('screening_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_id_token_jti'), ['id_token_jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_approvals_state_param'), ['state_param'], unique=True)

    op.create_table('approval_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_events_approval_id'), ['approval_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('engagement_id', sa.String(length=32), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount_micro', sa.BigInteger(), nullable=False),
    sa.Column('from_addr', sa.String(length=64), nullable=True),
    sa.Column('to_addr', sa.String(length=64), nullable=True),
    sa.Column('tx_hash', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('screening_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('mandates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('root_id', sa.String(length=32), nullable=False),
    sa.Column('engagement_id', sa.String(length=32), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('grantee_agent_public_id', sa.String(length=16), nullable=False),
    sa.Column('budget_micro', sa.BigInteger(), nullable=False),
    sa.Column('spent_micro', sa.BigInteger(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mandates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mandates_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mandates_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mandates_root_id'), ['root_id'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('payout_address', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('screening_address', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('manifest_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manifest_hash', sa.String(length=66), nullable=True))
        batch_op.add_column(sa.Column('manifest_stamped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('manifest_stamp_approval_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('manifest_stamp_sub', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ens_name', sa.String(length=255), nullable=True))

    _backfill_agent_public_ids()

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def _backfill_agent_public_ids():
    conn = op.get_bind()
    agents = sa.table('agents', sa.column('id', sa.Integer), sa.column('public_id', sa.String))
    for (agent_id,) in conn.execute(sa.select(agents.c.id)).all():
        conn.execute(agents.update().where(agents.c.id == agent_id)
                     .values(public_id=from_db_id(agent_id)))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_public_id'))
        batch_op.drop_column('ens_name')
        batch_op.drop_column('manifest_stamp_sub')
        batch_op.drop_column('manifest_stamp_approval_id')
        batch_op.drop_column('manifest_stamped_at')
        batch_op.drop_column('manifest_hash')
        batch_op.drop_column('manifest_json')
        batch_op.drop_column('screening_address')
        batch_op.drop_column('payout_address')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('mandates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mandates_root_id'))
        batch_op.drop_index(batch_op.f('ix_mandates_parent_id'))
        batch_op.drop_index(batch_op.f('ix_mandates_engagement_id'))

    op.drop_table('mandates')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_engagement_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('approval_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_events_approval_id'))

    op.drop_table('approval_events')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_state_param'))
        batch_op.drop_index(batch_op.f('ix_approvals_id_token_jti'))
        batch_op.drop_index(batch_op.f('ix_approvals_engagement_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenings_engagement_id'))

    op.drop_table('screenings')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_engagement_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('ens_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ens_names_parent_name'))

    op.drop_table('ens_names')
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagements_parent_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_engagements_buyer_human_id'))
        batch_op.drop_index(batch_op.f('ix_engagements_agent_id'))

    op.drop_table('engagements')
    op.drop_table('used_id_token_jtis')
    with op.batch_alter_table('humans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_humans_world_sub'))

    op.drop_table('humans')
    # ### end Alembic commands ###
